CREATE TABLE IF NOT EXISTS books(
id INT PRIMARY KEY AUTO_INCREMENT,
author VARCHAR(255) NOT NULL,
title VARCHAR(255) NOT NULL,
price NUMERIC(6, 2) NOT NULL);

CREATE TABLE IF NOT EXISTS cds(
id INT PRIMARY KEY AUTO_INCREMENT,
size INTEGER NOT NULL,
price NUMERIC(6, 2) NOT NULL);