INSERT INTO MOTORCYCLE(ID, ENGINE, TOPSPEED, MANUFACTURER, MODEL) VALUES (1, 800, 177, 'KAWASAKI', 'W800')
INSERT INTO MOTORCYCLE(ID, ENGINE, TOPSPEED, MANUFACTURER, MODEL) VALUES (2, 350, 130, 'JAVA', '638')
INSERT INTO MOTORCYCLE(ID, ENGINE, TOPSPEED, MANUFACTURER, MODEL) VALUES (3, 1200, 193, 'BONNEVILLE', 'T120')